### ISSUE TITLE
Incorrect prices synced to GMC when store rates are prices inclusive of tax

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#2220] opened 2024-01-26 11:43 UTC
### Describe the bug:

When the store's **Prices entered with tax** setting is set to `Yes, I will enter prices inclusive of tax`, incorrect prices different from the store's product prices are synced to Google Merchant Center. GL&A seems to be ignoring the price that exists in the core Woo price field and dynamically syncing different rates. 

### Screenshot of tax settings

![JOBd7O.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/cb4418ec-5639-4c33-9341-169a1d8aa20c)

### Screenshot of tax rates

![BRByVm.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/59903ebe-b28b-48db-a2fe-386e5e83ef7e)
(Random tax rates were entered for testing purposes)

### Products prices

![s5f3t5.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/cc1ea198-e2f0-4fe2-a387-69e376581ba5)

### Product prices in GMC

![FVtSQ9.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/ff74d059-87cd-4faf-b18d-716696e886eb)

### Steps to reproduce:

1. Go to WooCommerce > Settings > Taxes, under "Prices entered with tax" select `Yes, I will enter prices inclusive of tax`
2. Define tax rates for multiple countries, e.g. UK, Australia, Malta, US
3. Set up Google Listings & Ads and select multiple locations as target countries.  e.g. UK, Australia, Malta, US
4. Allow products to sync to GMC and notice the product prices don't match the store's default price. 

### Expected behavior:

The price in GMC should be the same as the store's default price. GL&A needs to consistently sync the price that exists in the Woo price field:

![pkgrj2.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/639d5d6c-013e-45da-b998-7c5ab0c09457)

Price is less by 20 USD in GMC:

![nFXpnF.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/33465e19-c1de-4470-8c1d-bc936eb308a4)

**Comment by sukafia** [comment] 2024-01-26 11:58
I updated my tax settings to `No, I will enter prices exclusive of tax` and pushed a fresh sync and the correct prices were synced:

![RnNSOF.png](https://github.com/woocommerce/google-listings-and-ads/assets/60121732/e3a90f13-7c65-4ff5-9258-263cb2aa3989)

I tested using the [experimental tax behaviour](https://github.com/woocommerce/woocommerce/wiki/How-Taxes-Work-in-WooCommerce#prices-including-tax---experimental-behavior) snippet and it didn't help. My assumption was that since the experimental behaviour ensures the store's default rate is shown on the store, that it'd help with the issue but it didn't have any effect on GMC rates for me.

**Comment by mikkamp** [comment] 2024-01-26 14:20
Just to clarify in the scenario described above the store base country is set to US. Prices for stores with a base country and target country set to US or CA sync prices "excluding" tax. Any other countries would sync prices "including" tax.

So if we look at this scenario we have 20% tax for US. So this is what we would expect:

Product Price | Calculation | Synced Price
-- | -- | --
$120 | `120 ÷ 1.2 = 100` | $100 
$40 | `40 ÷ 1.2 = 33.33` | $33.33 
$35 | `35 ÷ 1.2 = 29.17` | $29.17 
$70 | `70 ÷ 1.2 = 58.33` | $58.33

That matches the scenario above. However it turns out that in the original reported error the store base location was set to UK. So we'll need to replicate that scenario instead. 

In the original scenario it's syncing price equivalent to US price with tax. Basically what a US customer would see on the site after entering shipping address - taxes are calculated based on shipping address. However that would be unexpected as it should be using the store base country.

One thought would be that it's somehow picking up a customer object with a shipping address set to the US, when the sync is done. Not an expected scenario, but something to rule out. The other option is a conflicting plugin, possible candidates in this scenario:
- EAS EU compliance
- Price by country

**Comment by mikkamp** [comment] 2024-01-31 14:45
User in 7566706-zen confirmed that they had the correct prices sync when deactivating the possibly conflicting plugins.

So I'm going to close this issue for now. Feel free to reopen if there are additional details about a scenario where the prices are not synced correctly.

**Closed as completed by mikkamp** 2024-01-31 14:45 UTC
Labels: type: bug
