### ISSUE TITLE
WP 6.1 Compatibility: Website not displaying correctly when Plugin is active

### ISSUE THREAD

**Issue by infogc** [woocommerce/google-listings-and-ads#1749] opened 2022-11-07 11:37 UTC
### Steps to reproduce:

1. Activation of "Google Listing and Ads" Plugin on WP website.
2. Expecting my website working, linked to ads and helping me with conversions.
3. No possibility of using ads and my shop website cannot be seen or used.

![bug](https://user-images.githubusercontent.com/117646003/200300829-6f102155-219d-42bf-befb-e785783f994a.jpg)

**Comment by mikkamp** [comment] 2022-11-07 12:07
Hi @infogc we are still working on some minor issues with WordPress 6.1 so we haven't marked it as fully compatible yet. Although it shouldn't prevent your shop/website from working.

Do you have some more details about the errors? For example if you go to WooCommerce > Status > Logs. Are there some more details in the fatal error logs? Or if you open up the developer tools in your browser, do you see any specific console errors?

In addition to that, I wanted to point out that this repository is not intended for support requests. The best place to start the process is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can start a chat or open a ticket on [WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/). I'd suggest to include your [system status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/#system-status) as well as additional details to reproduce the issue.

The support team will help guide you through some problem solving and get some more information to give us a bit more context/background on your concerns/report above.

**Comment by mikkamp** [comment] 2023-02-15 14:45
Closing this issue as full WordPress 6.1 was added in version 2.2.1 (15th November 2022).

**Closed as completed by mikkamp** 2023-02-15 14:45 UTC
