### ISSUE TITLE
[Products on backorder] use the US standard date and time format, instead of the shop's

### ISSUE THREAD

**Issue by anastas10s-afk** [woocommerce/google-listings-and-ads#1800] opened 2022-12-01 09:46 UTC
## User story

With the release of version 1.4.0 of this plugin, a tweak was added, to [use the WordPress date and time formats on the Product Feed page](https://github.com/woocommerce/google-listings-and-ads/blob/develop/changelog.txt#L377).

While this might be fine for when products are available at a WooCommerce store, things get tricky in the case of availability dates for products on backorder.

That is, since Google requests US formatted date and time and shops outside the US have their own (different) setting selected under Settings > General.

### Is your feature request related to a problem? 

This has store-wide impact, since stores would have to change their date and time format to the US one, for having their products on backorder displayed on Google.

### Describe the solution you'd like 

The date and time settings under Settings > General to be decoupled/reformatted to US standard programmatically.

### Describe alternatives you've considered 

Some switch/option, available through the plugin's settings?

**Comment by anastas10s-afk** [comment] 2022-12-01 09:46
5753043-zen

**Comment by mikkamp** [comment] 2022-12-01 11:32
Thanks for the report, would you be able to clarify a bit more what is expected?

When editing the product we use a generic browser [date input](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date) field. The format there depends on what language / localization setting have been set for the browser or system defaults. So a US date / time format would only appear for someone with US settings.

When the value is saved it is passed in the standard ISO format of `YYYY-MM-DD`

I have my system set to EU formats so when I set the field it shows up as DD/MM/YYYY
![image](https://user-images.githubusercontent.com/11388669/205037940-4c34f62c-7947-4d23-8f25-6401403c1c3c.png)

When it's saved in the database it uses the ISO format: `2022-12-14T00:00:00+00:00`
And sends the same through the API.

After syncing to the Google Merchant Center it's received in the same format:
![image](https://user-images.githubusercontent.com/11388669/205039202-0ad422d0-c293-4828-9db1-f5054d28bf80.png)

Although it shows it in a local timezone for the product details (PST = UTC-8, so it's showing 8 hours earlier):
![image](https://user-images.githubusercontent.com/11388669/205039466-2b9e7c83-0f6a-487c-a5c3-5d8643dad166.png)

So what I'd like to clarify is, if inputting the date is the format that's expected to change?
Currently sticking to browser localization formats instead of what's set in WordPress > Settings > General

Or if it's expected to have the error message from Google translated to a format that matches the format on the Attributes tab?

As for the ticket I think it would be best to ask them to check the raw attributes section for a product in their Google Merchant Center, as well as checking how the meta data `_wc_gla_availabilityDate` is getting saved, as it seems somewhere along the line this gets converted incorrectly (which I'm unable to reproduce locally).

**Comment by gomlers** [comment] 2022-12-02 03:33
EDIT: 
I tried changing the date to something that was not as far into the future. When Google updated the product, the problem had gone away.

The issue was that my availability date was too far into the future.

I am sorry for the misunderstanding - AND that poor google is struggling to give correct error messages.

I will let my original post stay, in case it's interesting.

-------

I'm having trouble with this in my stores.

Where I add the date in Product Edit -> Google Listings & Ads:
![image](https://user-images.githubusercontent.com/43383853/205207691-e9116d20-2b4f-43db-9f5f-f6304fca476e.png)

In the Raw Feed Attributes it seems to be correct:
![image](https://user-images.githubusercontent.com/43383853/205208164-da1f3d15-7742-459e-bf57-7e5a4a1c11b8.png)

In the DB, it seems to also be correct?
![image](https://user-images.githubusercontent.com/43383853/205209037-af36f432-de91-4f7f-912a-eeda2419039f.png)

But Google still flags the product as an error-product (this is the same product as the Raw Feed example above):
![image](https://user-images.githubusercontent.com/43383853/205208347-010938ef-18db-4f3e-8673-0bba6e1ef66f.png)
1. Missing Attribute [date for availability]
2. Not a valid date, and / or time [date for availability]
ÅÅÅÅ-MM-DD means YYYY-MM-DD

And here is some more information about the product:
![image](https://user-images.githubusercontent.com/43383853/205208535-c9d3ccc7-5a6e-41d9-aff6-89f21e714f48.png)


And here you can see that I have 7 products like this right now in my store:
![image](https://user-images.githubusercontent.com/43383853/205208598-a6233698-2257-4648-9a43-bd462c303c9d.png)

Here is my Time/Date settings in Wordpress - General:
![image](https://user-images.githubusercontent.com/43383853/205208734-fc419514-7fe9-4b9e-9643-ca04393b0b20.png)

**Comment by gomlers** [comment] 2022-12-02 03:42
Unless the actual problem here is that the date is too far into the future, and that poor google is struggling to give proper error messages..

I will try to change the date, and let you know what happens.

**Comment by mikkamp** [comment] 2022-12-02 09:11
Thanks @gomlers for the detailed explanation.

Seems like it is mentioned in the [Google docs about this field](https://support.google.com/merchants/answer/6324470?hl=en):
> Required if you set the [availability [availability] ](https://support.google.com/merchants/answer/6324448)attribute to preorder or backorder. (You can then provide the date (up to 1 year in the future) when your product will be shipped using the availability date [availability_date] attribute).

It would be nice to add some validation to this field before it's synced to Google to ensure it isn't set further then 1 year in the future. We have issue #571 already tracking attribute validation so I'll add a note there.

@anastas10s-afk I'll go ahead and close this issue since the initial scope is not clear, and the root of the problem seems to have been the date being too far in the future. Feel free to reopen it if there is something concrete that needs to be changed.

**Closed as completed** 2022-12-02 09:12 UTC
Labels: type: enhancement, needs feedback

**Comment by anastas10s-afk** [comment] 2022-12-02 09:38
It would be nice to add some validation to this field, indeed.
Thank you for looking further into this, @mikkamp.
