### ISSUE TITLE
Policy compliance check failing due to store address

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#1782] opened 2022-11-17 22:19 UTC
### Describe the bug:

On the setup flow, the **[Confirm your store is live and accessible to all users](https://woocommerce.com/document/google-listings-and-ads/compliance-policy/#store-is-live)** policy compliance check is using the store's address for validation. 

This means that you may meet all the policy checklists but not entering your full store address will result in your inability to complete the setup. (The "Continue" button isn't clickable)

### Steps to reproduce:

1. Ensure your store meets all the policy checklist
2. Go to WooCommerce > Settings > Store Address (section) > leave your address line empty and enter city, state, and postcode.
3. Attempt the extension setup and notice the "Continue" button isn't clickable
4. Refresh the page and you'll notice "Confirm your store is live and accessible to all user" is automatically unchecked (Other checklists that passed the check will remain checked)

### Expected behavior:

"Confirm your store is live and accessible to all user" should check that the website is live and accessible to all. e.g, the website isn’t on maintenance mode and can be accessed by visitors.

### Actual behavior:

It's checking that the store address is fully entered.

#### Missing store address

![O9vKeV.png](https://user-images.githubusercontent.com/60121732/202570990-f8aaaeaa-8a4d-4b6a-a300-3e766a8d4cd0.png)

#### Issue on the checkout

![xGb8KV.png](https://user-images.githubusercontent.com/60121732/202571158-393aa127-424a-4d86-a4e7-9518ff58cae0.png)

- Related issue: [Improve setup flow policy compliance checks](https://github.com/woocommerce/google-listings-and-ads/issues/1781)

**Comment by mikkamp** [comment] 2022-11-18 15:52
That's interesting, because that check doesn't actually use the address field.

It calls the WC `get_allowed_countries` to get a list of countries the site sells to, and then checks if all the target countries we selected in the previous onboarding step are on that list.

It seems if the option `woocommerce_allowed_countries` is not set (probably the case on initial install of a WC site), it defaults to only a specific list of included countries. I think we would need to confirm if that option is saved on initial install, and whether updating the store address forced it to be saved with the default value of `all`, because that would change the outcome of the check.

We'd need to do some more testing to validate what's happening here, and whether it's an inconsistency to report in WooCommerce or if there is a way to work around it.

**Comment by sukafia** [comment] 2022-11-18 21:09
Affected users:

5677396-zd-woothemes
5713900-zd-woothemes
https://wordpress.org/support/topic/unable-to-connect-25/

**Comment by mikkamp** [comment] 2022-12-20 11:28
Thanks for the references to existing tickets, I took some time to look through those and confirmed that none of them is a case of the Policy Compliance checks blocking the onboarding. There are three main reasons why it is not the Policy Compliance checks:

1. The policy compliance checks do not check the store address, so setting the store address does not allow any of the policy compliance checks to pass (where it was failing previously with the store address unset).
2. The policy compliance checks are there as an assistance to automatically check, since they are not able to confirm all scenarios the user is able to manually verify and check the box that a compliance check passed. So if all policy compliance checks are confirmed they can continue.
3. In the onboarding step "Confirm store requirements" there are three sections which need to be filled out before the continue button becomes enabled. Phone Number, Store Address, Confirm policy compliance checks. So the store address not being filled out completely is related to the second section.

Following are some screenshots which confirm that it's directly related to the Store Address section (in the tickets I also found screenshots of incomplete addresses).

1. Store address is not filled out completely (street address is missing), some policy compliance checks fail which can be confirmed manually:

![image](https://user-images.githubusercontent.com/11388669/208653972-44c42fe4-1d5b-414f-8294-e76ce3476139.png)

2. Store address is not filled out completely (street address is missing), policy compliance checks have been confirmed manually, but continue button is still disabled:

![image](https://user-images.githubusercontent.com/11388669/208654176-57305eee-f19a-4680-9bc3-de6dc87a07f3.png)

3. Store address is filled out completely, some policy compliance checks fail which can be confirmed manually. Until they are confirmed the continue button remains disabled:

![image](https://user-images.githubusercontent.com/11388669/208654339-dc8d8f91-c223-4e75-a7f8-1ecb268ee6eb.png)

4. Store address is filled out completely, policy compliance checks have been confirmed manually. Now the continue button becomes enabled since all checks on the page are completed (not shown in screenshots but phone number must also be verified):

![image](https://user-images.githubusercontent.com/11388669/208654527-12447a8c-d6a5-4a60-8bc4-9c65038d7f47.png)

Based on the analysis above, I'm going to close this issue since it is not related to the policy compliance checks. I've added this specific scenario to issue https://github.com/woocommerce/google-listings-and-ads/issues/634 so we can track the need for improving error validation messages in one issue.

**Closed as completed by mikkamp** 2022-12-20 11:28 UTC
Labels: type: bug
