### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by M6Gpower** [woocommerce/google-listings-and-ads#1632] opened 2022-08-16 14:19 UTC
### Describe the bug:
At 3. Configure your product listings, the page is loading and after that i get a blank screen.

Consol error: 
-An error occurred while running 'mapSelect': undefined is not an object (evaluating 'r.woocommerce_default_country.split')
-TypeError: Right side of assignment cannot be destructured
-Unhandled Promise Rejection: TypeError: Right side of assignment cannot be destructured

**Comment by mikkamp** [comment] 2022-08-18 13:59
Thanks for the report @M6Gpower 

Others have noticed this problem in the past in combination with WooCommerce version 6.5, however the problem was resolved in WooCommerce 6.7. Would you be able to confirm what version of WooCommerce you are running on your site and whether upgrading to the latest version of WooCommerce 6.8 resolves the issue for you?

**Comment by M6Gpower** [comment] 2022-08-19 11:38
> Thanks for the report @M6Gpower
> 
> Others have noticed this problem in the past in combination with WooCommerce version 6.5, however the problem was resolved in WooCommerce 6.7. Would you be able to confirm what version of WooCommerce you are running on your site and whether upgrading to the latest version of WooCommerce 6.8 resolves the issue for you?

Dear, everything is up to date. WooCommerce is 6.8.1

**Comment by mikkamp** [comment] 2022-08-19 12:10
Thanks for the reply. We would however need some concrete steps to reproduce the issue, to be able to help you further.

Given that, I wanted to point out that this repository is not intended for support requests. The best place to start the process is with the [WordPress.org Google Listings and Ads forum](https://wordpress.org/support/plugin/google-listings-and-ads/) or if you have a WooCommerce.com account, you can start a chat or open a ticket on [WooCommerce.com support](https://woocommerce.com/my-account/create-a-ticket/). I'd suggest to include your [system status report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/#system-status) as well as additional details to reproduce the issue.

The support team will help guide you through some problem solving and get some more information to give us a bit more context/background on your concerns/report above.

**Closed as completed by mikkamp** 2022-08-19 12:10 UTC

**Comment by mikkamp** [comment] 2022-08-22 08:12
In retrospect we did find an additional issue: https://github.com/woocommerce/google-listings-and-ads/pull/1642
Based on the report it might also resolve the issue you were seeing here. We are hoping to release this fix soon.
