### ISSUE TITLE
Cannot complete setup/onboarding process

### ISSUE THREAD

**Issue by aheckler** [woocommerce/google-listings-and-ads#884] opened 2021-07-14 14:03 UTC
### Describe the bug:

Setup/onboarding process cannot be completed. When I get to this screen, clicking Continue doesn't do anything. JS errors in console:

![Markup on 2021-07-14 at 09:57:59](https://user-images.githubusercontent.com/5512652/125634831-aea34045-03a2-4b29-b8eb-539ae6773df5.png)

### Expected behavior:

The Continue button should work and setup should be able to complete normally.

### Actual behavior:

These JS errors are thrown:

```
`woocommerce_shared_settings` filter in Blocks is deprecated. See https://github.com/woocommerce/woocommerce-gutenberg-products-block/blob/trunk/docs/contributors/block-assets.md
onSubmitCallback is deprecated and will be removed from @woocommerce/components in version 5.1.2. Please use onSubmit instead.
```

### Steps to reproduce:

1. WC test site with GLA installed. You'll also need a Google account.
2. Go through the onboarding process as normal, connecting all accounts, etc. with the browser console open, watching for errors.
3. After configuring the options, you'll get to the screen I included above, and the Continue button won't work. JS errors thrown.

### Additional details:

Brought up in 30631888-hc / 4138929-zen, but I replicated it on our GLA test site. Existing forums threads:

https://wordpress.org/support/topic/can-not-complete-set-up/?view=all
https://wordpress.org/support/topic/cannot-complete-configuration/?view=all (maybe?)
https://wordpress.org/support/topic/complete-setup-button-does-not-work/?view=all

**Comment by mikkamp** [comment] 2021-07-14 14:15
Reproducible with either WooCommerce 5.5 or a newer version of WooCommerce Admin (>= 2.4)

**Comment by eason9487** [comment] 2021-07-14 14:34
The working laptop is not with me, so I can't actually test it. Would it be fixed if don't use the sharing dependency of **@woocommerce/components** with WC/WC-admin?

1. Remove
    https://github.com/woocommerce/google-listings-and-ads/blob/88ac79b3decba7a39d4b3cbf006d25b606b5ae6d/webpack.config.js#L19
    https://github.com/woocommerce/google-listings-and-ads/blob/88ac79b3decba7a39d4b3cbf006d25b606b5ae6d/webpack.config.js#L28
2. restart `npm start`

If yes, maybe we can consider having a hotfix before resolving the compatibility problems.

**Comment by eason9487** [comment] 2021-07-14 14:52
https://github.com/woocommerce/woocommerce-admin/blob/v2.4.0/packages/components/src/form/index.js#L104-L114

`onSubmitCallback` is deprecated, but it should still be workable. Seems it's not the root cause.

**Comment by tomalec** [comment] 2021-07-14 15:17
I think the problem is both `onSubmit` and `onSubmitCallback` are defined for some reason. I'll investigate it for 30-60mins more, if I won't find the root cause, I'd try detaching shared dependency as [suggested above](https://github.com/woocommerce/google-listings-and-ads/issues/884#issuecomment-879946317)

**Comment by tomalec** [comment] 2021-07-14 15:19
Ok so the root cause is faulty deprecation handling in `Form` component, as it sets the default value of `onSubmit: () => {},` so which is always truthy. Then the default noop is called in case `onSubmitCallback` is provided.

I'll fix it on our end by providing both callbacks. 

Respective issue in `woocommerce/components` https://github.com/woocommerce/woocommerce-admin/issues/7351

**Comment by EricaKuschel** [comment] 2021-07-14 17:24
Adding ticket here for follow up: 4139132-zen
* Customer cannot update email currently which would allow the site to match the Google Merchant Center.

**Comment by tomalec** [comment] 2021-07-14 18:24
GLA workaround is ready at https://github.com/woocommerce/google-listings-and-ads/pull/885.
I'll work on the actual fix in `woocommerce/components` for other plugins tomorrow https://github.com/woocommerce/woocommerce-admin/issues/7351

**Comment by zhollenbeak** [comment] 2021-07-14 22:59
Another ticket 4137257-zen

**Comment by solstudioim** [comment] 2021-07-14 23:55
The user in this ticket seems to be affected: 4086698-Zen

**Comment by eason9487** [comment] 2021-07-15 03:00
Thank you all for the report! [1.2.1](https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.2.1) has been released for fixing this critical issue.

Resolved by #885

**Closed as completed by eason9487** 2021-07-15 03:00 UTC
Labels: type: bug, priority: critical

**Comment by aheckler** [comment] 2021-07-15 09:26
I followed up on all the tickets posted here just now.

**Comment by tomalec** [comment] 2021-07-26 08:51
The fix for WooCommerce Admin bug was merged and will be published in the upcoming release.
https://github.com/woocommerce/woocommerce-admin/pull/6708
