### ISSUE TITLE
“availibility” unknown “enum-value”

### ISSUE THREAD

**Issue by findingsimple** [woocommerce/google-listings-and-ads#1058] opened 2021-10-21 05:25 UTC
Noticed the [following topic](https://wordpress.org/support/topic/ungultiger-enum-wert-in-feld-availability/) in the support forums

```
Hi, since the last update it seems Google has problems with the field “availibility” and finds an unknown “enum-value”. (Google Search Concole)

This problem started at October 1st (since last update of the plugin) and grew up to all my products.

I guess this has something to do with the latest:

“Add – Allow backorder stock availability for products.” ???

Please fix….
```

I haven't had a chance to investigate so posting here for follow up

**Comment by nima-karimi** [comment] 2021-11-05 11:18
Seems like the problem was caused to another plugin because it also happens when they've disabled GLA: https://wordpress.org/support/topic/ungultiger-enum-wert-in-feld-availability/#post-15038872

However, when I checked [Google's doc for the `Availability` field](https://support.google.com/merchants/answer/6324448?hl=en) I noticed the supported values for `in stock` and `out of stock` have changed a bit. They've changed to `in_stock` and `out_of_stock` (with an underscore instead of space)

<img width="743" alt="image" src="https://user-images.githubusercontent.com/73110514/140501038-9083037e-e390-41e7-b43e-1baa1dde7276.png">

This shouldn't cause any issues though because I can confirm that the previous values still work and products' availability status is synced correctly. It's probably a backward-compatible change by Google.

I've created a  PR to change the values to the ones suggested in Google documentation though just to be aligned with them: https://github.com/woocommerce/google-listings-and-ads/pull/1081

Closing this issue as the user has [reported](https://wordpress.org/support/topic/ungultiger-enum-wert-in-feld-availability/#post-15038872) it is likely caused by another plugin.

**Closed as completed by nima-karimi** 2021-11-05 11:18 UTC
Labels: type: bug, priority: high, needs investigation
