### ISSUE TITLE
Google listing & ads plugin disable jQuery when deactivate/delete

### ISSUE THREAD

**Issue by ghost** [woocommerce/google-listings-and-ads#1045] opened 2021-10-12 14:45 UTC
Hello there,

I am using Google listing & ads plugin which is developed by woo commerce, i have few issues.

I use google listing & ads plugin with api integration so google merchant center pull product automatically from production. when i copy site from production into staging. again all product pull from staging and make duplicate into google merchant center.
if i disconnect all accounts in staging it will automatically disconnect from production.
if i deactivate/delete google listing & ads plugin into staging then its disable jQuery some functions not working in my site

please advise how to handle this.

**Comment by findingsimple** [comment] 2021-10-12 14:48
Duplicate of https://github.com/woocommerce/google-listings-and-ads/issues/1044

**Closed as completed by findingsimple** 2021-10-12 14:48 UTC

**Comment by ghost** [comment] 2021-10-12 14:57
Excuse me ?! did you read what response i've got ?

**Comment by ghost** [comment] 2021-10-12 14:58
@juliaamosova suggest to post issue to this repository, How did u delete ?

**Comment by findingsimple** [comment] 2021-10-12 15:04
@juliaamosova moved the issue to this repo #1044 - so there was no need to create a new issue (this one)

**Comment by ghost** [comment] 2021-10-13 06:04
ok thank u @jconroy
