### ISSUE TITLE
Value for "Last updated" on the "Product Feed" tab is incorrect

### ISSUE THREAD

**Issue by Kheiden** [woocommerce/google-listings-and-ads#802] opened 2021-06-21 20:07 UTC
### Describe the bug:
The time value in the "Last updated" UI element has been updated over the weekend, but the date is incorrect and hasn't been updated accordingly. 

### Expected behavior:
I expect the value "Last updated" to be correct for date as well as time. 

### Actual behavior:
The value for the time has changed over the weekend, but the value for date has not.

### Steps to reproduce:
1. I was running a pre-launch build of the GFL&A plugin (v0.5.6) on a WooCommerce installation
2. I took this screenshot of the Product Feed page
![image](https://user-images.githubusercontent.com/8250577/122818529-2ef61400-d28e-11eb-8762-a302749d05e0.png)
3. I upgraded the extension to the `trunk` branch of the GFL&A plugin.
4. I took this screenshot today (Monday)
![image](https://user-images.githubusercontent.com/8250577/122818579-3cab9980-d28e-11eb-9fd8-b8903596da4d.png)

**Comment by mikkamp** [comment] 2021-06-22 06:57
I can reproduce that and it's because the date is formatted as `n F Y, h:ia`

n = Numeric representation of a month, without leading zeros

It should be day of the month instead.

Would it be hard to get the date/time format based off of the WordPress settings to show there? I like the 24 hour format.

**Comment by findingsimple** [comment] 2021-06-22 07:17
> it's because the date is formatted

Thanks @mikkamp is that clientside or serverside?

**Comment by mikkamp** [comment] 2021-06-22 07:20
Client side: https://github.com/woocommerce/google-listings-and-ads/blob/trunk/js/src/product-feed/product-statistics/status-box.js#L74

**Comment by eason9487** [comment] 2021-06-22 07:27
Need to replace the `n` by `j` 🙇‍♂️

**Comment by eason9487** [comment] 2021-06-22 09:34
Opened PR #804 to ship a quick fix with version 1.1. And we can consider applying datetime format of WP setting in later versions.

**Comment by nima-karimi** [comment] 2021-06-22 12:46
Closing this issue as the fix for it is merged in #804 and will be shipped in version 1.1.

Created a follow-up issue to update the format to be the same as WordPress date/time format: https://github.com/woocommerce/google-listings-and-ads/issues/805

**Closed as completed by nima-karimi** 2021-06-22 12:46 UTC
Labels: type: bug
