### ISSUE TITLE
WC 6.5 to 6.7 compatibility issue: Modal header border bottom is missing

### ISSUE THREAD

**Issue by ecgan** [woocommerce/google-listings-and-ads#1583] opened 2022-07-04 15:34 UTC
### Describe the bug:

I was doing compatibility testing with WooCommerce 6.7.0-beta.2 in https://github.com/woocommerce/google-listings-and-ads/issues/1577, and I noticed that the Modal component is missing the border / separator between the modal header title and modal body content. The border is missing because of some CSS from the WooCommerce core:

![image](https://user-images.githubusercontent.com/417342/177174314-464823d7-8e8e-4a42-b128-4995b9747e3a.png)

I tested previous WC versions and found out that the issue happens in WC 6.6.0 and 6.5.0 too.

In WC 6.4.0, the modal component shows up fine, with a border / separator between the modal header title and modal content:

![image](https://user-images.githubusercontent.com/417342/177173483-2f84a89c-1fb4-4be3-b93c-08daaf6396e5.png)

### Steps to reproduce:

1. Use WC 6.7.0-beta.2, 6.6.0 or 6.5.0. 
2. Open a modal in Google Listings and Ads, such as the Edit Free Listings modal shown above.

### Expected behavior:

There should be a border between the modal header and modal body, similar to @wordpress/components modal: https://wordpress.github.io/gutenberg/?path=/story/components-modal--default

<img width="409" alt="image" src="https://user-images.githubusercontent.com/417342/177185080-c43722fe-a58f-4606-b8e1-b4b2fa28f496.png">

### Actual behavior:

There is no border between the modal header and modal body.

### Additional details:

I have also created an issue in WooCommerce repo: https://github.com/woocommerce/woocommerce/issues/33720.

**Comment by wyter** [comment] 2022-08-19 06:48
Tested on WooCommerce 6.8.0 and could still replicate:
![Free listings](https://user-images.githubusercontent.com/11092629/185559754-2b1fdedd-f2ea-491e-8fbd-422d0e01b7fb.png)

However, following [this comment](https://github.com/woocommerce/woocommerce/issues/33720#issuecomment-1185101742), we can wait to see if version 6.9.0 fixes the issue and then close here.

**Comment by mikkamp** [comment] 2022-11-15 15:54
We are at WooCommerce 7.1 now and the WooCommerce issue has been resolved, with the CSS for a 0 border no longer being added: https://github.com/woocommerce/woocommerce/pull/33807

However when looking back at the expected behaviour I see that the WP component now behaves differently: https://wordpress.github.io/gutenberg/?path=/story/components-modal--default

![image](https://user-images.githubusercontent.com/11388669/201961636-314d888c-d974-427f-bdfa-c79802f547e0.png)

![image](https://user-images.githubusercontent.com/11388669/201961796-1db719e2-8727-4597-981f-0d6ee9847288.png)

Based on this PR, it seems it's an intended design choice: https://github.com/WordPress/gutenberg/pull/40781
Closing this issue as there isn't any further action to take.

**Closed as completed by mikkamp** 2022-11-15 15:54 UTC
Labels: type: bug, priority: normal
