### ISSUE TITLE
Shipping time country select input does not update and validate correctly

### ISSUE THREAD

**Issue by nima-karimi** [woocommerce/google-listings-and-ads#1387] opened 2022-03-31 09:13 UTC
### Describe the bug:

When editing a free listing, the shipping time country selector input will not get updated based on the countries selected at the previous step in the onboarding wizard. It seems to retain the values previously entered by the user (and stored in the database).

This leads to another issue where if a user changes the target countries but keeps the number of countries selected by this input to the same, the validator passes and allows the user to save their shipping settings.

### Steps to reproduce:

1. First, enter US and AU as your target countries and then set a delivery date for them and save your free listing.
2. Then edit the free listing and in the "Choose your audience" step, change the countries to DE and NL
3. Go back to the shipping step and confirm that the input is not updated and you can save settings without entering a shipping time for DE and NL
4. Also on the shipping step, click on the edit and confirm you can still enter shipping times for countries NOT in your target countries list

### Expected behavior:
Even if we choose to keep the previously entered countries in the list, I think the validation should not pass and also once the user changes the target countries, they should be notified to enter shipping times for them.

### Actual behavior:
The shipping time country selector is not updated once the user changes their target countries and they can also save the settings without entering a shipping time for the new target countries.

**Comment by ecgan** [comment] 2022-04-07 14:28
Duplicate of issue #1304, closing this issue.

**Closed as completed by ecgan** 2022-04-07 14:28 UTC
Labels: type: bug
