### ISSUE TITLE
The single product displayed on the "Show" field doesn't match the selected one

### ISSUE THREAD

**Issue by eason9487** [woocommerce/google-listings-and-ads#541] opened 2021-05-04 04:23 UTC
### Describe the bug:

Found from https://github.com/woocommerce/google-listings-and-ads/pull/540#issuecomment-831459305.

@ecgan reported:

> When I was testing this, I changed the "Show" field to "Single Product", search for a product ("Cap", with id 18), upon clicking on the product result, the dropdown changed to another unrelated product ("WordPress Pennant" with id 35). See video below (https://d.pr/v/yd3d8H):

> https://user-images.githubusercontent.com/417342/116918762-e5704c00-ac82-11eb-8b8d-121154e02134.mp4

> Here's the problematic request and response, from the browser dev tools:

```
GET https://gla1.test/wp-json/wc-analytics/products?include=18&per_page=1&_locale=user

[{"id":35,"name":"WordPress Pennant","slug":"wordpress-pennant","permalink":"https:\/\/gla1.test\/product\/wordpress-pennant\/","date_created":"2021-02-05T15:47:09","date_created_gmt":"2021-02-05T15:47:09","date_modified":"2021-02-05T15:47:37","date_modified_gmt":"2021-02-05T15:47:37","type":"external","status":"publish","featured":false,"catalog_visibility":"visible","description":"<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n","short_description":"<p>This is an external product.<\/p>\n","sku":"wp-pennant","price":"11.05","regular_price":"11.05","sale_price":"","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":false,"purchasable":false,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":0,"download_expiry":0,"external_url":"https:\/\/mercantile.wordpress.org\/product\/wordpress-pennant\/","button_text":"Buy on the WordPress swag store!","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"backorders":"no","backorders_allowed":false,"backordered":false,"sold_individually":false,"weight":"","dimensions":{"length":"","width":"","height":""},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0.00","rating_count":0,"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":21,"name":"Decor","slug":"decor"}],"tags":[],"images":[{"id":58,"date_created":"2021-02-05T15:47:37","date_created_gmt":"2021-02-05T15:47:37","date_modified":"2021-02-05T15:47:37","date_modified_gmt":"2021-02-05T15:47:37","src":"https:\/\/gla1.test\/wp-content\/uploads\/2021\/02\/pennant-1.jpg","name":"pennant-1.jpg","alt":""}],"attributes":[],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"price_html":"<span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>11.05<\/bdi><\/span>","related_ids":[],"meta_data":[{"id":653,"key":"_wpcom_is_markdown","value":"1"}],"_links":{"self":[{"href":"https:\/\/gla1.test\/wp-json\/wc-analytics\/products\/35"}],"collection":[{"href":"https:\/\/gla1.test\/wp-json\/wc-analytics\/products"}]}}]
```

### Expected behavior:

The single product displayed on the "Show" field should be the same as the selected one.

### Actual behavior:

The single product displayed on the "Show" field doesn't match the selected one

### Steps to reproduce:

N/A (see **Additional details** below)

### Additional details:
@eason9487 couldn't replicate the problem on his local env.

> I'm unable to replicate the problem by the same operating steps. And the fetched report data will not affect the state of "Show" field nor the URL query. I will open an issue for us to track it.

> Operate the same steps on my end:

> https://user-images.githubusercontent.com/17420811/116957424-6bfc4c00-acca-11eb-8d6d-cfb50451415a.mp4

**Comment by findingsimple** [comment] 2021-08-17 05:26
Adding to the next patch release milestone - if it can't be replicated lets close the issue instead of having it hang around

**Comment by eason9487** [comment] 2021-08-18 03:32
I still can't reproduce it. Hey @ecgan, could you help to check it?

**Comment by ecgan** [comment] 2021-08-19 08:42
@eason9487 , I'll take a look at it. 👌

**Comment by ecgan** [comment] 2021-08-19 18:49
I am not able to reproduce this issue, seems everything is working fine now. 

Related to the "problematic request and response" mentioned in the issue description, here's what I got in my local environment now:

```text
// request for product ID 18.
GET https://gla1.test/wp-json/wc-analytics/products?include=18&per_page=1&_locale=user

// respond back with expected product ID 18.
[{"id":18,"name":"Cap","slug":"cap","permalink":"https:\/\/gla1.test\/product\/cap\/","date_created":"2021-02-05T15:47:08","date_created_gmt":"2021-02-05T15:47:08","date_modified":"2021-03-30T13:19:26","date_modified_gmt":"2021-03-30T13:19:26","type":"simple","status":"publish","featured":true,"catalog_visibility":"visible","description":"<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.<\/p>\n","short_description":"<p>This is a simple product.<\/p>\n","sku":"woo-cap","price":"12300.6789","regular_price":"12345.6789","sale_price":"12300.6789","date_on_sale_from":null,"date_on_sale_from_gmt":null,"date_on_sale_to":null,"date_on_sale_to_gmt":null,"on_sale":true,"purchasable":true,"total_sales":0,"virtual":false,"downloadable":false,"downloads":[],"download_limit":0,"download_expiry":0,"external_url":"","button_text":"","tax_status":"taxable","tax_class":"","manage_stock":false,"stock_quantity":null,"backorders":"no","backorders_allowed":false,"backordered":false,"low_stock_amount":null,"sold_individually":false,"weight":"","dimensions":{"length":"","width":"","height":""},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":0,"reviews_allowed":true,"average_rating":"0.00","rating_count":0,"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"purchase_note":"","categories":[{"id":19,"name":"Accessories","slug":"accessories"}],"tags":[],"images":[{"id":47,"date_created":"2021-02-05T15:47:22","date_created_gmt":"2021-02-05T15:47:22","date_modified":"2021-02-05T15:47:22","date_modified_gmt":"2021-02-05T15:47:22","src":"https:\/\/gla1.test\/wp-content\/uploads\/2021\/02\/cap-2.jpg","name":"cap-2.jpg","alt":""}],"attributes":[{"id":1,"name":"Color","position":0,"visible":true,"variation":false,"options":["Yellow"]}],"default_attributes":[],"variations":[],"grouped_products":[],"menu_order":0,"price_html":"<del aria-hidden=\"true\"><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>12,345.68<\/bdi><\/span><\/del> <ins><span class=\"woocommerce-Price-amount amount\"><bdi><span class=\"woocommerce-Price-currencySymbol\">&#36;<\/span>12,300.68<\/bdi><\/span><\/ins>","related_ids":[19,17,33,16],"meta_data":[{"id":501,"key":"_wpcom_is_markdown","value":"1"},{"id":721,"key":"_wc_gla_visibility","value":"sync-and-show"},{"id":958,"key":"_wc_gla_sync_status","value":"synced"},{"id":994,"key":"_wc_gla_mc_status","value":"disapproved"},{"id":1426,"key":"_wc_gla_synced_at","value":"1629391516"},{"id":1427,"key":"_wc_gla_google_ids","value":{"US":"online:en:US:gla_18"}}],"stock_status":"instock","_links":{"self":[{"href":"https:\/\/gla1.test\/wp-json\/wc-analytics\/products\/18"}],"collection":[{"href":"https:\/\/gla1.test\/wp-json\/wc-analytics\/products"}]}}]
```

Demo video: (https://d.pr/v/z7Vsio)

https://user-images.githubusercontent.com/417342/130126943-3d5f470c-d5c7-4fc5-8750-c8204562c593.mp4

It is working as expected. Closing this issue.

**Closed by ecgan** 2021-08-19 18:49 UTC
Labels: type: bug, priority: low, reporting, needs tests
