### ISSUE TITLE
Jetpack connection can't be disconnected via the hidden page

### ISSUE THREAD

**Issue by sukafia** [woocommerce/google-listings-and-ads#1434] opened 2022-04-19 09:24 UTC
### Describe the bug:

The extension hidden page is used to connect as well as disconnect existing connections. However, while testing the recent update, the Jetpack connection can't be disconnected from that page: https://d.pr/i/amHuCz

This suggests the Jetpack connection can't be disconnected at all in the extension (Except all connections are disconnected using the "disconnect all button"). Being able to disconnect and reconnect Jetpack is important because disconnecting existing connections from the hidden page, etc, is known to help when there's a connection/setup issue (e.g the setup can't be completed).

1. Setup the plugin 
2. Go to the hidden page. - example.com/wp-admin/admin.php?page=connection-test-admin-page
3. Click the "Disconnect Jetpack" button
4. The connection remains connected so the prompt to reconnect Jetpack isn't shown

### Expected behavior:

* Clicking "Disconnect Jetpack" from the hidden page should disconnect the existing Jetpack connection, allowing for the new prompt to reconnect Jetpack to be shown on the extension's page.

### Actual behavior:

The connection remains despite the button to "disconnect Jetpack" being clicked.

**Comment by mikkamp** [comment] 2022-04-29 06:04
This issue was discussed here: p1650357847631659-slack-C01E9LB4X61

It seems the reason it wasn't disconnecting fully is because of another extension (WCPay) also using the Jetpack connection. In this case GLA just does a "soft" disconnect which only removes itself from the list of connected apps, the Jetpack connection remains connected.

In order to fully disconnect, each of the connected apps must disconnect itself, but we might need to do some further testing to ensure that actually happens as intended, and whether that's a smooth process. Should we return the list of other apps connected as an indicator what to do next?

Also if the disconnect removes itself from the list of connected apps, but we continue to use the Jetpack connection (since it's still connected for other apps), then does this put it in an odd state?

**Comment by findingsimple** [comment] 2022-05-09 06:52
Noting that a PR was recently merged https://github.com/Automattic/jetpack/pull/23991 that Deprecated the soft disconnect functionality and then later reverted https://github.com/Automattic/jetpack/pull/24104 because it was breaking connections on a number of sites.

This issue identified that we should probably revisit how we're handling the connection in general - so I'll create a project internally for us to revisit in a future cycle

**Closed as completed** 2022-06-21 08:58 UTC
Labels: type: enhancement, priority: normal, needs investigation

**Comment by ianlin** [comment] 2022-06-21 09:03
### Updates 21st June 2022

According to the suggestions from @leogermani in https://github.com/woocommerce/google-listings-and-ads/pull/1559#issuecomment-1153916454 as well as in the project post pcTzPl-AG-p2#comment-1247, we have decided to keep the original "soft disconnect" behaviour when the user tries to disconnect Jetpack connection in both GLA's settings page and the connection test page. If the user wants to fully disconnect Jetpack connection while there are other plugins using the connection, [they should use "My Jetpack" from the Jetpack plugin](https://jetpack.com/support/getting-started-with-jetpack/my-jetpack/).

In the PR #1559 it adds an enhancement in the connection test page that will be showing the reason why Jetpack connection cannot be disconnected, it will look like this:

<img width="897" alt="Screenshot 2022-06-21 at 14 38 21" src="https://user-images.githubusercontent.com/914406/174733666-a35958f2-d24d-49c7-aadd-ea63bc5af3f2.png">

**Comment by ianlin** [comment] 2022-06-22 07:21
Just a heads-up this was released in [1.13.6](https://github.com/woocommerce/google-listings-and-ads/releases/tag/1.13.6) by @jorgemd24.
